version: '3.8'

services:
  restgdf_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: restgdf_api
    container_name: restgdf_api
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:8080"
    working_dir: /home/appuser/restgdf_api
    command: ["gunicorn", "app:app"]
  lab:
    build:
      context: .
      dockerfile: Dockerfile-lab
    image: restgdf_api_lab
    container_name: restgdf_api_lab
    env_file:
      - .env
    ports:
      - "${JUPYTER_PORT:-8081}:8081"
    volumes:
      - ./lab:/home/appuser/lab
    working_dir: /home/appuser/lab
    command: ["jupyter", "lab", "--ip", "0.0.0.0", "--port", "8081", "--no-browser"]
