version: '3.8'

services:
  restgdf_api:
    image: restgdf_api:latest
    build: .
    container_name: restgdf_api
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    working_dir: /home/appuser/restgdf_api
    command: ["gunicorn", "app:app"]
